name: Publish Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  documentation:
      uses: sensirion/.github/.github/workflows/driver.python.documentation.yml@main
      with:
       build-python-version: 3.8
